# NixOS configuration for the vfkit linux builder microVM.
# Replaces the QEMU-based nix.linux-builder on macOS; uses Apple Virtualization.framework.
# Access: ssh -i /etc/nix/builder_ed25519 builder@linux-builder.local
{
  pkgs,
  lib,
  inputs,
  ...
}:
let
  # macOS 26 broke virtio-serial,stdio ("operation not supported by device").
  # Wrap vfkit to redirect the VM serial console to a log file instead.
  # The file is written relative to CWD (the STATE_DIR set by builder up).
  hostPkgs = inputs.nixpkgs.legacyPackages.aarch64-darwin;
  vfkitWrapped = hostPkgs.writeShellScriptBin "vfkit" ''
    args=()
    i=0
    argv=("$@")
    while [ "$i" -lt "''${#argv[@]}" ]; do
      arg="''${argv[$i]}"
      next="''${argv[$((i+1))]:-}"
      if [ "$arg" = "--device" ] && [ "$next" = "virtio-serial,stdio" ]; then
        args+=("--device" "virtio-serial,logFilePath=console-hvc0.log")
        i=$((i+2))
      else
        args+=("$arg")
        i=$((i+1))
      fi
    done
    exec ${hostPkgs.vfkit}/bin/vfkit "''${args[@]}"
  '';
in
{
  microvm.hypervisor = "vfkit";
  microvm.vfkit.package = vfkitWrapped;
  microvm.vcpu = 4;
  microvm.mem = 4096;

  # NAT networking — host can connect to the guest's vmnet IP; guest has internet access.
  microvm.interfaces = [
    {
      type = "user";
      id = "eth0";
      mac = "02:00:00:00:00:0b";
    }
  ];

  # Darwin host packages so the vfkit runner correctly detects the macOS host.
  microvm.vmHostPackages = inputs.nixpkgs.legacyPackages.aarch64-darwin;

  # Persistent writable overlay so the nix store survives reboots.
  microvm.writableStoreOverlay = "/nix/.rw-store";
  microvm.volumes = [
    {
      mountPoint = "/nix/.rw-store";
      image = "builder-nix-store.img";
      size = 30000;
    }
  ];

  boot.initrd.systemd.enable = true;

  networking.hostName = "linux-builder";

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # Publishes linux-builder.local via mDNS; macOS Bonjour resolves it automatically.
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish = {
      enable = true;
      addresses = true;
    };
  };

  users.users.builder = {
    isSystemUser = true;
    group = "builder";
    shell = pkgs.bash;
    openssh.authorizedKeys.keys = [
      # /etc/nix/builder_ed25519.pub — generated by nix-darwin, reused here.
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG+jVQ6GrUm+kd7OHj0tM8xD8dF82pOyarLvKkSUUH+d builder@localhost"
    ];
  };
  users.groups.builder = { };

  nix.settings = {
    trusted-users = [
      "root"
      "builder"
    ];
    min-free = 1024 * 1024 * 1024;
    max-free = 3 * 1024 * 1024 * 1024;
  };

  system.stateVersion = "24.05";
}
